name: CI/CD Pipeline - DEVELOPMENT

on:
  push:
    branches:
      - dev

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: mlops-deploy-repository
  ECR_REGISTRY: 804923754854.dkr.ecr.us-east-1.amazonaws.com
  IMAGE_TAG: dev-latest
  CLUSTER_NAME: mlops-deploy-cluster
  SERVICE_NAME: mlops-deploy-dev
  S3_BUCKET: mlops-project-deploy-bucket
  S3_TEST_PATH: test_data/

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - run: pip install -r requirements.txt

      - run: |
          mkdir -p test_data
          aws s3 cp s3://${{ env.S3_BUCKET }}/${{ env.S3_TEST_PATH }} test_data/ --recursive
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest tests/


  build_and_deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | \
          docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

      - name: Build & Push Image
        run: |
          IMAGE="${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Force new ECS deployment
        run: |
          aws ecs update-service \
            --cluster ${{ env.CLUSTER_NAME }} \
            --service ${{ env.SERVICE_NAME }} \
            --force-new-deployment
